# Generated by Django 3.2.5 on 2022-12-18 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20221218_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='shop_name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='address',
            new_name='supplier_address',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='name',
            new_name='supplier_name',
        ),
        migrations.AlterField(
            model_name='shop',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shop_detail', to='inventory.supplier'),
        ),
    ]
